# Generated by Django 4.2 on 2026-08-13 06:46

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыланган убакыт')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email адреси')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефон номери')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Сүрөт')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Биография')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Эркек'), ('F', 'Аял'), ('O', 'Башка')], max_length=1, verbose_name='Жынысы')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Төрөлгөн күнү')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Шаар')),
                ('country', models.CharField(default='Кыргызстан', max_length=100, verbose_name='Өлкө')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('social_id', models.CharField(blank=True, max_length=255, verbose_name='Социалдык сеть ID')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email текшерилген')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Телефон текшерилген')),
                ('is_public', models.BooleanField(default=True, verbose_name='Жарыя профили')),
                ('newsletter', models.BooleanField(default=True, verbose_name='Newsletter-ге жазылуу')),
            ],
            options={
                'verbose_name': 'Пайдалануучу',
                'verbose_name_plural': 'Пайдалануучулар',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыланган убакыт')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Белсүү')),
                ('title', models.CharField(max_length=255, verbose_name='Аталышы')),
                ('description', models.TextField(blank=True, verbose_name='Сыпаттамасы')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='Сүрөт')),
                ('link', models.URLField(blank=True, verbose_name='Сылтама')),
                ('placement', models.CharField(choices=[('homepage', 'Башкы бет'), ('sidebar', 'Каптал панели'), ('top', 'Өңү жакын'), ('bottom', 'Төмөнү жакын')], default='homepage', max_length=20, verbose_name='Орду')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сорту')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Баштоо убакыты')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Аяктоо убакыты')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннерлер',
                'ordering': ['placement', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыланган убакыт')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Белсүү')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Аталышы')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Сыпаттамасы')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='Икона')),
                ('color', models.CharField(default='#000000', help_text='Hex color code', max_length=7, verbose_name='Түсү')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сорту')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыланган убакыт')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Белсүү')),
                ('name', models.CharField(max_length=200, verbose_name='Аталышы')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=300, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Билдирүү')),
                ('status', models.CharField(choices=[('new', 'Жаңы'), ('read', 'Окулган'), ('replied', 'Жооп берилген'), ('closed', 'Жабык')], default='new', max_length=20, verbose_name='Статусу')),
                ('reply', models.TextField(blank=True, verbose_name='Жооп')),
            ],
            options={
                'verbose_name': 'Байланыш билдирүүсү',
                'verbose_name_plural': 'Байланыш билдирүүлөрү',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Администратор'), ('editor', 'Редактор'), ('moderator', 'Модератор'), ('scholar', 'Аалым'), ('user', 'Пайдалануучу')], max_length=50, unique=True, verbose_name='Аталышы')),
                ('description', models.TextField(blank=True, verbose_name='Сыпаттамасы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убакыт')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Рольдор',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255, unique=True, verbose_name='Бет аталышы')),
                ('page_url', models.SlugField(unique=True, verbose_name='Бет URL')),
                ('meta_title', models.CharField(max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.CharField(max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='OG Image')),
                ('twitter_title', models.CharField(blank=True, max_length=255, verbose_name='Twitter Title')),
                ('twitter_description', models.CharField(blank=True, max_length=160, verbose_name='Twitter Description')),
                ('twitter_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='Twitter Image')),
                ('structured_data', models.JSONField(blank=True, null=True, verbose_name='Структурланган маалымат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыланган убакыт')),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadatalar',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыланган убакыт')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Белсүү')),
                ('site_title', models.CharField(default='Муфтияттын Исламий Портали', max_length=255, verbose_name='Сайттын аталышы')),
                ('site_description', models.TextField(default='Кыргызстандагы исламий маалымат порталы', verbose_name='Сайттын сыпаттамасы')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Логосу')),
                ('site_icon', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Сайт икона')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Дареги')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Жөндөө режими')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Жөндөө билдирүүсү')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=255, verbose_name='Google Maps API ачы')),
            ],
            options={
                'verbose_name': 'Сайт конфигурациясы',
                'verbose_name_plural': 'Сайт конфигурациялары',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыланган убакыт')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Белсүү')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Аталышы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тегдер',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='core_tag_slug_4ab57c_idx'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Өндүрүшүнүн мээстери'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', '-created_at'], name='core_contac_status_a0adbc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email'], name='core_contac_email_cfac76_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='core_catego_slug_a504e5_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='core_user_usernam_e8adca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_id_4f05c9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='core_user_is_acti_8c954f_idx'),
        ),
    ]
